services:
  vortex-api:
    build: ./server
    container_name: vortex-api
    command: npm run start:api 
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      - redis
      - minio
    networks:
      - vortex-network

  vortex-worker:
    build: ./server
    container_name: vortex-worker
    command: npm run start:worker
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      - redis
      - minio
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    networks:
      - vortex-network

  redis:
    image: redis:alpine
    container_name: vortex-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "mish::3791"]
    networks:
      - vortex-network
  minio:
    image: minio/minio
    container_name: vortex-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    volumes:
      - minio_data:/data
    networks:
      - vortex-network

networks:
  vortex-network:
    driver: bridge

volumes:
  minio_data: