services:
  vortex-api:
    build: 
      context: ./server
      dockerfile: Dockerfile.api
    restart: always  
    container_name: vortex-api
    command: npm run start:api 
    ports:
      - "80:8080"
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - vortex-network

  vortex-worker:
    build: 
      context: ./server
      dockerfile: Dockerfile.worker
    container_name: vortex-worker
    command: npm run start:worker
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    networks:
      - vortex-network

  redis:
    image: redis:alpine
    restart: always
    container_name: vortex-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - vortex-network

networks:
  vortex-network:
    driver: bridge

volumes:
  minio_data: